apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myredis
  name: myredis
spec:
  selector:
    matchLabels:
      app: myredis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myredis
    spec:
      containers:
      - image: localhost:32000/myredis
        name: myredis
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myredis
  name: myredis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: myredis
